In [1]:
import pandas as pd
import seaborn as sns

In [2]:
# Load Data
insurance_data = pd.read_csv("insurance.csv")

In [3]:
x = insurance_data.drop(columns=["charges"])
y = insurance_data["charges"]

# One Hot Encoding
x = pd.get_dummies(x, columns=["region"], drop_first=True, dtype=int);

x["sex"] = x["sex"].map({"female" : 0, "male" : 1})
x["smoker"] = x["smoker"].map({"no" : 0, "yes" : 1})

x.head()

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,0,0,1
1,18,1,33.770,1,0,0,1,0
2,28,1,33.000,3,0,0,1,0
3,33,1,22.705,0,0,1,0,0
4,32,1,28.880,0,0,1,0,0

In [4]:
# Train Test Split

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

x_train.head()

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
560,46,0,19.95,2,0,1,0,0
1285,47,0,24.32,0,0,0,0,0
1142,52,0,24.86,0,0,0,1,0
969,39,0,34.32,5,0,0,1,0
486,54,0,21.47,3,0,1,0,0

In [5]:
# Train Model

from sklearn.linear_model import LinearRegression
from sklearn.metrics  import r2_score

model = LinearRegression()
model.fit(x_train, y_train)

# Predict Values
y_pred = model.predict(x_test)

# Evaluate
r2 = r2_score(y_test, y_pred);
print("r-squared : ", r2)

r-squared :  0.7835929767120724

In [6]:
# Interaction Feature

x["age_smoker"] = x["age"] * x["smoker"]
x["bmi_smoker"] = x["bmi"] * x["smoker"] 

x.head()

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest,age_smoker,bmi_smoker
0,19,0,27.900,0,1,0,0,1,19,27.9
1,18,1,33.770,1,0,0,1,0,0,0.0
2,28,1,33.000,3,0,0,1,0,0,0.0
3,33,1,22.705,0,0,1,0,0,0,0.0
4,32,1,28.880,0,0,1,0,0,0,0.0

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train)

# Predict Values
y_pred = model.predict(x_test)

# Evaluate
r2 = r2_score(y_test, y_pred);
print("r-squared : ", r2)

r-squared :  0.865231697953168